# a first workflow attempt
name: My First Workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name:  Greet the User
        run: |
          echo "Hello world from ${{ vars.WHO_TO_GREET }}"
          echo "my secret is ${{secrets.MY_SECRET}}
        shell: bash
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - run: tree
    
  
      
      
