# a first workflow attempt
name: My First Workflow
on: 
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  first_job:
    name: My First Job
    runs-on: ubuntu-latest
    steps:
      - name:  Greet the User
        run: |
          echo "Hello world from ${{ vars.WHO_TO_GREET }}"
          sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
          echo "My secret is '$sec'."
        shell: bash
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - run: tree
  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: first_job
    steps:
      - run: echo "from Test"
  Load-Test:
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: first_job
    steps:
      - run: echo "from Load-Test"
  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.nt
    needs:
      - Test
      - Load-Test
    steps:
      - run: echo "from Production"
    
  
      
      
